# Generated by Django 5.2.8 on 2025-11-13 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="execution_time",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="periodicity",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="time",
        ),
    ]
