# Generated by Django 5.2.8 on 2025-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Часовой пояс пользователя (например, Europe/Moscow, UTC)",
                max_length=50,
                verbose_name="Часовой пояс",
            ),
        ),
    ]
