# Generated by Django 5.2.8 on 2025-11-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_initial"),
        ("notifications", "0002_add_reminder_frequency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания уведомления",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="habit",
            field=models.ForeignKey(
                help_text="Привычка, о которой отправляется уведомление",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="habits.habit",
                verbose_name="Привычка",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(
                default=False,
                help_text="Статус отправки уведомления",
                verbose_name="Отправлено",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата фактической отправки уведомления",
                null=True,
                verbose_name="Дата отправки",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, которому отправляется уведомление",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
