# Generated by Django 5.2.8 on 2025-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="execution_time",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Время на выполнение в секундах",
                verbose_name="Время на выполнение",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Периодичность выполнения в днях (от 1 до 7)",
                verbose_name="Периодичность",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="time",
            field=models.TimeField(
                default="09:00:00",
                help_text="Время выполнения привычки",
                verbose_name="Время",
            ),
        ),
    ]
