# Generated by Django 5.2.8 on 2025-11-13 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0004_notification_execution_time_notification_periodicity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Время выполнения привычки",
                verbose_name="Время",
            ),
        ),
    ]
