# Generated by Django 5.2.8 on 2025-11-13 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notification_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="reminder_frequency",
        ),
    ]
